// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ictwmuisxhiwzzbfzodp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljdHdtdWlzeGhpd3p6YmZ6b2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTQ5NzMsImV4cCI6MjA1Nzc3MDk3M30.WQx6vGCjUvNb-cQYNZBSIvwPxhccU8G9hjsC7bdAGKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);