
// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

// Mock Supabase client that does nothing
// This is just a placeholder to prevent import errors in existing code
// All actual data will now come from our mock services
const SUPABASE_URL = "https://mock-supabase-url.com";
const SUPABASE_PUBLISHABLE_KEY = "mock-key";

// Create a mock supabase client that does nothing
export const supabase = {
  from: () => ({
    select: () => ({
      eq: () => ({
        single: () => Promise.resolve({ data: null, error: null }),
        maybeSingle: () => Promise.resolve({ data: null, error: null }),
        count: () => Promise.resolve({ count: 0, error: null }),
        head: () => Promise.resolve({ count: 0, error: null }),
        then: (callback: any) => Promise.resolve(callback({ data: null, error: null }))
      }),
      then: (callback: any) => Promise.resolve(callback({ data: null, error: null }))
    })
  }),
  auth: {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: null, error: null, subscription: { unsubscribe: () => {} } }),
    signIn: () => Promise.resolve({ data: null, error: null }),
    signOut: () => Promise.resolve({ error: null })
  },
  functions: {
    invoke: () => Promise.resolve({ data: null, error: null })
  },
  storage: {
    from: () => ({
      upload: () => Promise.resolve({ data: null, error: null }),
      getPublicUrl: () => ({ data: { publicUrl: '' } })
    })
  }
};
